export const JOB_TITLE_GROUPS: { label: string; options: string[] }[] = [
  {
    label: "Logística / Supply Chain",
    options: [
      "Gerente de Logística",
      "Coordenador de Logística",
      "Supervisor de Logística",
      "Analista de Logística",
      "Gerente de Supply Chain",
      "Coordenador de Supply Chain",
      "Supply Chain Manager",
      "Gerente de Transportes",
      "Coordenador de Transportes",
      "Gerente de Distribuição",
      "Coordenador de Distribuição",
      "Gerente de Armazém / Warehouse Manager",
      "Coordenador de Almoxarifado",
      "Gerente de Compras",
      "Procurement Manager",
      "Comprador Técnico",
    ],
  },
  {
    label: "Operações Industriais",
    options: [
      "Gerente de Operações",
      "Coordenador de Operações",
      "Diretor de Operações",
      "Operations Manager",
      "Plant Manager",
      "Gerente Industrial",
      "Coordenador Industrial",
      "Supervisor de Produção",
      "Gerente de Produção",
      "Coordenador de Produção",
      "Gerente de Manutenção",
      "Coordenador de Manutenção",
      "Engenheiro de Processos",
      "Engenheiro de Produção",
      "Engenheiro Industrial",
    ],
  },
  {
    label: "TI / Tecnologia",
    options: [
      "Gerente de TI",
      "Coordenador de TI",
      "Diretor de TI",
      "IT Manager",
      "CIO",
      "CTO",
      "Analista de Sistemas",
      "Analista de Infraestrutura",
      "Coordenador de Infraestrutura",
      "Gerente de Projetos de TI",
      "Product Owner",
      "Especialista em Sistemas",
      "Analista de ERP",
      "Consultor ERP",
      "Analista de Dados",
      "BI Analyst",
      "Business Intelligence Manager",
    ],
  },
  {
    label: "Decisores / C-Level",
    options: [
      "CEO",
      "COO",
      "Diretor Industrial",
      "Diretor de Logística",
      "Diretor de Supply Chain",
      "Head de Operações",
      "Head de Logística",
      "Head de Supply Chain",
      "Head de Tecnologia",
    ],
  },
  {
    label: "Outro",
    options: ["Outro"],
  },
];
